---
# https://docs.mergify.com/configuration/

pull_request_rules:
  - name: Automatically merge PRs from Dependabot
    conditions:
      - base=dev
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=build / build"
      - check-skipped=sign
      - -conflict
      - label=automerge
    actions:
      delete_head_branch:
      merge:
        method: squash

