---
name: Delete Untagged Container Images

# on:
#   schedule:
#     - cron: '10 */1 * * *' # yamllint disable-line rule:quoted-strings

on:
  workflow_dispatch:

permissions: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/delete-untagged
      - name: Delete Untagged
        uses: camargo/delete-untagged-action@v1
        with:
          github-token: ${{ secrets.GH_PAT }}
          personal-account: true

