---
name: container image builder

on: push

concurrency:
  # group: ${{ github.workflow }}-${{ github.ref }}
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      actions: read
      contents: write
      packages: write

    # uses: jsloan117/test-templates/.github/workflows/docker-build-template.yml@main
    uses: ./.github/workflows/docker-build-template.yml
    secrets:
      dockerhub-username: ${{ github.actor }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: false
      push: false
      load: true
      provenance: false
      sbom: false
      image: ${{ github.repository }}

  scan:
    permissions:
      actions: read
      contents: read
      security-events: write

    # uses: jsloan117/test-templates/.github/workflows/scan.yml@main
    uses: ./.github/workflows/scan.yml
    needs: build
    with:
      sbom-file: ${{ needs.build.outputs.sbom-artifact-name }}

  sign:
    permissions:
      actions: read
      contents: read

    if: github.event_name != 'pull_request'

    # uses: jsloan117/test-templates/.github/workflows/sign.yml@main
    uses: ./.github/workflows/sign.yml
    needs: build
    secrets:
      cosign-key: ${{ secrets.COSIGN_KEY }}
      cosign-password: ${{ secrets.COSIGN_KEYPASS }}
      dockerhub-username: ${{ github.actor }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      dockerhub-enable: false

