---
name: docker build v2

on: push

concurrency:
  # group: ${{ github.workflow }}-${{ github.ref }}
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: docker build v2x

    permissions:
      contents: read
      packages: write

    # uses: jsloan117/test-templates/.github/workflows/build.yml@main
    uses: ./.github/workflows/docker-build-template.yml
    secrets:
      dockerhub-username: ${{ github.actor }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      cosign-key: ${{ secrets.COSIGN_KEY }}
      cosign-password: ${{ secrets.COSIGN_KEYPASS }}
    with:
      dockerhub-enable: true
      cosign-sign-enable: false
      cosign-verify-enable: false
      cosign-upload-key: false
      push: false
      load: true
      provenance: false
      sbom: false
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      # build-args: |
      #   BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
      #   VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      #   REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}

  job2:
    name: job 2

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: check digest
        env:
          digest: ${{ needs.build.outputs.digest }}
          imgs: ${{ needs.build.outputs.imgs }}
          sbom: ${{ needs.build.outputs.sbom }}
        run: |
          echo "digest for image: ${digest}"
          echo
          echo "sbom name: ${sbom}"
          echo

          for i in $imgs; do
            echo -e "\nimage_list: $i"
          done

      # https://github.com/marketplace/actions/download-a-build-artifact
      - uses: actions/download-artifact@v4

      - run: pwd; ls -lh; ls -lh ./sbom

  # scan:
  #   uses: jsloan117/test-templates/.github/workflows/scan.yml@main
  #   needs: build
  #   with:
  #     sbom: ${{ needs.build.outputs.sbom }}
  #     # images: ${{ needs.build.outputs.imgs }}

  # scan:
  #   uses: jsloan117/test-templates/.github/workflows/scan.yml@main
  #   needs: build
  #   with:
  #     images: ${{ steps.meta.outputs.json }}

