---
name: container image builder

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main
  release:
    types: released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    permissions:
      actions: read
      contents: write
      packages: write

    uses: jsloan117/test-templates/.github/workflows/docker-build-template.yml@main
    secrets:
      dockerhub-username: ${{ github.actor }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: false
      provenance: false
      sbom: false
      image: ghcr.io/${{ github.repository }}

  scan:
    permissions:
      actions: read
      contents: read
      security-events: write

    uses: jsloan117/test-templates/.github/workflows/scan.yml@main
    needs: build
    with:
      sbom-file: ${{ needs.build.outputs.sbom-artifact-name }}

  sign:
    permissions:
      actions: read
      contents: read
      packages: write

    if: github.event_name != 'pull_request'

    uses: jsloan117/test-templates/.github/workflows/sign.yml@main
    needs: build
    secrets:
      cosign-key: ${{ secrets.COSIGN_KEY }}
      cosign-password: ${{ secrets.COSIGN_KEYPASS }}
      dockerhub-username: ${{ github.actor }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      dockerhub-enable: false

