---
name: cosign

on:
  workflow_call:
    inputs:
      image:
        description: image to sign/verify
        default: ${{ github.repository }}
        required: false
        type: string

      digest:
        description: digest to sign/verify
        default: ''
        required: false
        type: string

      cosign-sign-enable:
        description: enable cosign signing
        default: true
        required: false
        type: boolean

      cosign-verify-enable:
        description: enable cosign verifying
        default: true
        required: false
        type: boolean

      cosign-upload-key:
        description: enable cosign upload key
        default: true
        required: false
        type: boolean

      dockerhub-enable:
        description: login to dockerhub
        default: false
        required: false
        type: boolean

      ghcr-enable:
        description: login to ghcr
        default: true
        required: false
        type: boolean

    secrets:
      cosign-key:
        description: cosign private key
        required: false

      cosign-password:
        description: cosign private key password
        required: false

      dockerhub-token:
        description: dockerhub token
        required: false

      dockerhub-username:
        description: dockerhub username
        required: false

    outputs:
      publickey-artifact-id:
        description: GitHub ID of an Artifact, can be used by the REST API
        value: ${{ jobs.scan.outputs.publickey-artifact-id }}

      publickey-artifact-url:
        description: URL to download the artifact
        value: ${{ jobs.scan.outputs.publickey-artifact-url }}

permissions: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write

    outputs:
      publickey-artifact-id: ${{ steps.upload.outputs.artifact-id }}
      publickey-artifact-url: ${{ steps.upload.outputs.artifact-url }}

    steps:
      # https://github.com/marketplace/actions/cosign-installer
      - name: Install Cosign
        if: (github.event_name != 'pull_request' && inputs.cosign-sign-enable) || (github.event_name != 'pull_request' && inputs.cosign-verify-enable)
        uses: sigstore/cosign-installer@v3.5.0

      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && inputs.dockerhub-enable && inputs.cosign-sign-enable
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      # https://github.com/marketplace/actions/docker-login
      - name: Login to GHCR
        if: github.event_name != 'pull_request' && inputs.ghcr-enable && inputs.cosign-sign-enable
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign Image
        if: github.event_name != 'pull_request' && inputs.cosign-sign-enable
        run: |
          cosign sign -y -r --key env://COSIGN_KEY \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -a "ref=${{ github.ref_name }}" \
            ${IMAGE}@${DIGEST}
        env:
          IMAGE: ${{ inputs.image }}
          DIGEST: ${{ inputs.digest }}
          COSIGN_KEY: ${{ secrets.cosign-key }}
          COSIGN_PASSWORD: ${{ secrets.cosign-password }}

      - name: Verify Image
        if: github.event_name != 'pull_request' && inputs.cosign-verify-enable
        run: |
          printf '%s' "${COSIGN_PUBLIC_KEY}" > cosign.pub
          cosign verify --key env://COSIGN_PUBLIC_KEY ${IMAGE}@${DIGEST} | jq
        env:
          IMAGE: ${{ inputs.image }}
          DIGEST: ${{ inputs.digest }}
          COSIGN_PUBLIC_KEY: ${{ vars.COSIGN_PUB }}

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload Public Key
        if: github.event_name != 'pull_request' && inputs.cosign-upload-key
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: cosign.pub
          path: cosign.pub
          if-no-files-found: warn

