---
name: Tag and Release
# https://github.com/orgs/community/discussions/27194

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-tag
      # https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          create_annotated_tag: true

      # https://github.com/marketplace/actions/create-release
      # https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GH_PAT }} # using PAT to allow workflow to trigger release for docker-build.yml

