---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/contexts

name: called workflow
run-name: run name of called workflow

on:
  workflow_call:
    # allow reuse of this workflow in other repos
    inputs:
      file:
        description: Dockerfile to build, relative to context path
        default: Dockerfile
        required: false
        type: string

      images:
        description: A list of the account/repo names for docker build to push to
        default: |-
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: job name
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: split image names
        id: split-images
        shell: bash
        run: |
          # Split the input into an array
          IFS=$'\n' read -d '' image_names <<< "${{ inputs.images }}"
          echo "name=image_names::${image_names[@]}" >> ${GITHUB_OUTPUT}

      - name: loop
        run: |
          image_names=("${{ steps.split-images.outputs.image_names }}")
          echo ${{ inputs.file }}
          echo ${{ inputs.images }}
          for image_name in "${image_names[@]}"; do
            echo "Building and pushing image: $image_name"
          done

