---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/contexts

name: called workflow
run-name: run name of called workflow

on:
  workflow_call:
    # allow reuse of this workflow in other repos
    inputs:
      file:
        description: Dockerfile to build, relative to context path
        default: Dockerfile
        required: false
        type: string

      images:
        description: A list of the account/repo names for docker build to push to
        default: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: job name
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: loop
        run: |
          # IFS=$'\n' read -a image_names <<< "${{ inputs.images }}"
          read -rd '' -a image_names <<< "${{ inputs.images }}"
          for image in "${image_names[@]}"; do
            echo ${image}
          done

